"""Initial setup

Revision ID: a0519edaa707
Revises: 
Create Date: 2025-05-27 19:32:39.402031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0519edaa707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Adres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=False),
    sa.Column('typ_adresu', sa.String(length=50), nullable=False),
    sa.Column('imie', sa.String(length=50), nullable=True),
    sa.Column('nazwisko', sa.String(length=50), nullable=True),
    sa.Column('linia_adresu1', sa.String(length=100), nullable=False),
    sa.Column('linia_adresu2', sa.String(length=100), nullable=True),
    sa.Column('miasto', sa.String(length=50), nullable=False),
    sa.Column('kod_pocztowy', sa.String(length=20), nullable=False),
    sa.Column('kraj', sa.String(length=50), nullable=False),
    sa.Column('numer_telefonu', sa.String(length=20), nullable=True),
    sa.Column('domyslny', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['Uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Gatunek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('Kategoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('nadkategoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nadkategoria_id'], ['Kategoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('Promocja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_promocyjny', sa.String(length=50), nullable=True),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('znizka_procentowa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('znizka_kwotowa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_rozpoczecia', sa.DateTime(), nullable=False),
    sa.Column('data_zakonczenia', sa.DateTime(), nullable=True),
    sa.Column('aktywna', sa.Boolean(), nullable=True),
    sa.Column('minimalna_wartosc_zamowienia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('jednorazowy_na_uzytkownika', sa.Boolean(), nullable=True),
    sa.Column('max_uzyc', sa.Integer(), nullable=True),
    sa.Column('aktualne_uzycia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod_promocyjny')
    )
    op.create_table('SiteSetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('Uzytkownik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('haslo_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rola', sa.String(length=20), nullable=False),
    sa.Column('data_rejestracji', sa.DateTime(), nullable=True),
    sa.Column('imie', sa.String(length=50), nullable=True),
    sa.Column('nazwisko', sa.String(length=50), nullable=True),
    sa.Column('numer_telefonu', sa.String(length=20), nullable=True),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('ostatnie_logowanie', sa.DateTime(), nullable=True),
    sa.Column('reset_hasla_token', sa.String(length=128), nullable=True),
    sa.Column('reset_hasla_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('adres_domyslny_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adres_domyslny_id'], ['Adres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('Wydawnictwo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('Koszyk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=True),
    sa.Column('id_sesji', sa.String(length=128), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('data_modyfikacji', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['Uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sesji'),
    sa.UniqueConstraint('id_uzytkownika')
    )
    op.create_table('Ksiazka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('okladka_url', sa.String(length=255), nullable=True),
    sa.Column('gatunek_id', sa.Integer(), nullable=True),
    sa.Column('wydawnictwo_id', sa.Integer(), nullable=True),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rok_wydania', sa.Integer(), nullable=True),
    sa.Column('ilosc_stron', sa.Integer(), nullable=True),
    sa.Column('format_pliku', sa.String(length=50), nullable=True),
    sa.Column('rozmiar_pliku_mb', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sciezka_pliku', sa.String(length=255), nullable=False),
    sa.Column('dostepny', sa.Boolean(), nullable=True),
    sa.Column('data_dodania', sa.DateTime(), nullable=True),
    sa.Column('srednia_ocen', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('liczba_ocen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gatunek_id'], ['Gatunek.id'], ),
    sa.ForeignKeyConstraint(['wydawnictwo_id'], ['Wydawnictwo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('Powiadomienie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uzytkownika_zglaszajacego', sa.Integer(), nullable=True),
    sa.Column('id_uzytkownika_docelowego', sa.Integer(), nullable=True),
    sa.Column('rola_docelowa', sa.String(length=50), nullable=True),
    sa.Column('typ', sa.String(length=100), nullable=False),
    sa.Column('tresc', sa.Text(), nullable=False),
    sa.Column('link_docelowy', sa.String(length=255), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.Column('czy_przeczytane', sa.Boolean(), nullable=True),
    sa.Column('data_przeczytania', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_uzytkownika_docelowego'], ['Uzytkownik.id'], ),
    sa.ForeignKeyConstraint(['id_uzytkownika_zglaszajacego'], ['Uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Powiadomienie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Powiadomienie_czy_przeczytane'), ['czy_przeczytane'], unique=False)
        batch_op.create_index(batch_op.f('ix_Powiadomienie_data_utworzenia'), ['data_utworzenia'], unique=False)

    op.create_table('Zamowienie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=False),
    sa.Column('data_zamowienia', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('suma_calkowita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adres_rozliczeniowy_id', sa.Integer(), nullable=True),
    sa.Column('metoda_platnosci', sa.String(length=50), nullable=True),
    sa.Column('id_transakcji_platnosci', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['adres_rozliczeniowy_id'], ['Adres.id'], ),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['Uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DostepDoTresci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=False),
    sa.Column('id_ksiazki', sa.Integer(), nullable=False),
    sa.Column('id_zamowienia', sa.Integer(), nullable=False),
    sa.Column('data_udzielenia_dostepu', sa.DateTime(), nullable=True),
    sa.Column('token_pobierania', sa.String(length=128), nullable=True),
    sa.Column('liczba_pobran', sa.Integer(), nullable=True),
    sa.Column('limit_pobran', sa.Integer(), nullable=True),
    sa.Column('data_waznosci_tokenu', sa.DateTime(), nullable=True),
    sa.Column('format_pliku', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_ksiazki'], ['Ksiazka.id'], ),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['Uzytkownik.id'], ),
    sa.ForeignKeyConstraint(['id_zamowienia'], ['Zamowienie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_pobierania')
    )
    op.create_table('ElementKoszyka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_koszyka', sa.Integer(), nullable=False),
    sa.Column('id_ksiazki', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.Column('cena_w_momencie_dodania', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_dodania', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_koszyka'], ['Koszyk.id'], ),
    sa.ForeignKeyConstraint(['id_ksiazki'], ['Ksiazka.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ksiazka_Kategoria',
    sa.Column('id_ksiazki', sa.Integer(), nullable=False),
    sa.Column('id_kategorii', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kategorii'], ['Kategoria.id'], ),
    sa.ForeignKeyConstraint(['id_ksiazki'], ['Ksiazka.id'], ),
    sa.PrimaryKeyConstraint('id_ksiazki', 'id_kategorii')
    )
    op.create_table('Recenzja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uzytkownika', sa.Integer(), nullable=False),
    sa.Column('id_ksiazki', sa.Integer(), nullable=False),
    sa.Column('ocena', sa.Integer(), nullable=False),
    sa.Column('komentarz', sa.Text(), nullable=True),
    sa.Column('data_dodania', sa.DateTime(), nullable=True),
    sa.Column('zatwierdzona', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_ksiazki'], ['Ksiazka.id'], ),
    sa.ForeignKeyConstraint(['id_uzytkownika'], ['Uzytkownik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Zamowienie_Ksiazka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_zamowienia', sa.Integer(), nullable=False),
    sa.Column('id_ksiazki', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.Column('cena_jednostkowa_w_momencie_zakupu', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('format_pliku_zakupiony', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_ksiazki'], ['Ksiazka.id'], ),
    sa.ForeignKeyConstraint(['id_zamowienia'], ['Zamowienie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Zamowienie_Ksiazka')
    op.drop_table('Recenzja')
    op.drop_table('Ksiazka_Kategoria')
    op.drop_table('ElementKoszyka')
    op.drop_table('DostepDoTresci')
    op.drop_table('Zamowienie')
    with op.batch_alter_table('Powiadomienie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Powiadomienie_data_utworzenia'))
        batch_op.drop_index(batch_op.f('ix_Powiadomienie_czy_przeczytane'))

    op.drop_table('Powiadomienie')
    op.drop_table('Ksiazka')
    op.drop_table('Koszyk')
    op.drop_table('Wydawnictwo')
    op.drop_table('Uzytkownik')
    op.drop_table('SiteSetting')
    op.drop_table('Promocja')
    op.drop_table('Kategoria')
    op.drop_table('Gatunek')
    op.drop_table('Adres')
    # ### end Alembic commands ###
